name: Zip
description: Zip Folder/Files
inputs:
  files:
    description: 'Files to zip'
    required: true
  output:
    description: Zip filename
    required: true
  context:
    description: Working Directory
    required: false
    default: .
outputs:
  zip_file:
    description: 'Zip file'
    value: ${{ steps.zip.outputs.zip_file }}
runs:
  using: composite
  steps:
    -
      id: zip
      name: Zip Files
      shell: bash
      run: |
        # Prepare files list
        FILES=$(echo ${{ inputs.files }} | tr "," "\n" | xargs)
        ZIP_FILE="${{ inputs.output }}"

        cd ${{ inputs.context }}
        zip -qq -r "${ZIP_FILE}.zip" $FILES

        echo "::debug::$(unzip -l "${ZIP_FILE}.zip")"

        echo "::set-output name=zip_file::$ZIP_FILE"
